//User reduce types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED"
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED"
export const SET_USER = "SET_USER"
export const LOADING_USER = "LOADING_USER"
//UI reducer types
export const SET_ERRORS = "SET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_UI = "LOADING_UI"
//Data reducer types
export const GET_ALL_EMAILS = "GET_ALL_EMAILS"
export const FILTER_EMAILS = "FILTER_EMAILS"
export const CLEAR_FILTER_EMAILS = "CLEAR_FILTER_EMAILS"
export const SELECT_EMAIL = "SELECT_EMAIL"
export const SELECT_MULTIPLE_EMAILS = "SELECT_MULTIPLE_EMAILS"
export const CLEAR_SELECTED_EMAILS = "CLEAR_SELECTED_EMAILS"
export const SEND_EMAILS = "SEND_EMAILS"
export const CLEAR_SEND_EMAILS = "CLEAR_SEND_EMAILS"